const subscriptions = {
  currency: "BDT",
  billing: "monthly",
  plans: [
    {
      id: "basic",
      name: "Basic",
      price: 500,
      pricePerSession: 6,
      sessions: 1,
      description:
        "Perfect for individuals or small teams needing 1 WhatsApp number to connect with customers.",
      features: [
        "You can use 1 session",
        "Unlimited Contacts",
        "No Daily Message Cap",
        "MCP Server Integration",
        "Send to Users & Groups",
        "Send Text, Images, Files, Videos & Audio",
        "Send Documents, Reactions & Locations",
        "Full API Access",
        "Real-time Webhooks",
        "Priority Support",
      ],
      cta: "Manage Plan",
      highlighted: false,
    },
    {
      id: "pro",
      name: "Pro",
      price: 1500,
      pricePerSession: 5,
      sessions: 3,
      description:
        "Ideal for growing businesses managing up to 3 WhatsApp numbers to reach more customers.",
      features: [
        "You can use 3 sessions",
        "Unlimited Contacts",
        "No Daily Message Cap",
        "MCP Server Integration",
        "Send to Users & Groups",
        "Send Text, Images, Files, Videos & Audio",
        "Send Documents, Reactions & Locations",
        "Full API Access",
        "Real-time Webhooks",
        "Priority Support",
      ],
      cta: "Preview Upgrade",
      highlighted: true,
    },
    {
      id: "plus",
      name: "Plus",
      price: 3000,
      pricePerSession: 5,
      sessions: 6,
      description:
        "Great for expanding teams needing 6 WhatsApp numbers for better coverage and capacity.",
      features: [
        "You can use 6 sessions",
        "Unlimited Contacts",
        "No Daily Message Cap",
        "MCP Server Integration",
        "Send to Users & Groups",
        "Send Text, Images, Files, Videos & Audio",
        "Send Documents, Reactions & Locations",
        "Full API Access",
        "Real-time Webhooks",
        "Priority Support",
      ],
      cta: "Preview Upgrade",
      highlighted: false,
    },
    {
      id: "business",
      name: "Business",
      price: 4500,
      pricePerSession: 450,
      sessions: 10,
      description:
        "Full support for up to 10 WhatsApp numbers with advanced tools for larger companies.",
      features: [
        "You can use 10 sessions",
        "Unlimited Contacts",
        "No Daily Message Cap",
        "MCP Server Integration",
        "Send to Users & Groups",
        "Send Text, Images, Files, Videos & Audio",
        "Send Documents, Reactions & Locations",
        "Full API Access",
        "Real-time Webhooks",
        "Priority Support",
      ],
      cta: "Preview Upgrade",
      highlighted: false,
    },
  ],
};

export default subscriptions;
